Repository Amplitude-Developer-Docs/amplitude-dev-center, pull requests merged in 2022-09, with the labels that each got.

#267 DDI-220 Cron Job for Link Checking
  .github/workflows/cron-link-check.yml
  .github/workflows/mega-linter.yml
Labels: enhancement

#271 DDI-217 Add SendGrid Cohort doc
  .github/styles/Vocab/dev/accept.txt
  docs/data/destinations/sendgrid-cohort.md
  includes/data-destinations-cohorts.md
  mkdocs.yml
Labels: documentation

#273 DDI-227: Testing different quickstart format
  docs/data/sdks/index.md
  includes/sdk-quickstart/quickstart-check-for-success.md
  includes/sdk-quickstart/quickstart-complete-code-example.md
  includes/sdk-quickstart/quickstart-enforce-event-schema-intro.md
  includes/sdk-quickstart/quickstart-initialize-library.md
  includes/sdk-quickstart/quickstart-send-data.md
Labels: documentation

#270 Ddi 225.vale.typescript
  .github/styles/Amplitude/Acronyms.yml
  .github/styles/Amplitude/ComplexWords.yml
  .github/styles/Amplitude/HeadingGerunds.yml
  .github/styles/Amplitude/Headings.yml
  .github/styles/Amplitude/OptionalPlural.yml
  .github/styles/Amplitude/Passive.yml
  .github/styles/Amplitude/TooWordy.yml
  .github/styles/Amplitude/Vocab.yml
  .github/styles/Vocab/dev/accept.txt
  docs/data/sdks/typescript-browser/ampli.md
  docs/data/sdks/typescript-browser/index.md
  docs/data/sdks/typescript-browser/migration.md
  includes/abbreviations.md
Labels: documentation

#277 DXOC-188 fix android Amplitude reference and code formats in ampli
  docs/data/sdks/android-kotlin/ampli.md
  docs/data/sdks/android-kotlin/index.md
Labels: documentation

#278 Added throttling limits
  docs/analytics/apis/group-identify-api.md
Labels: documentation

#282 DDI-243 update considerations to reflect app changes"
  docs/data/destinations/marketo-cohort.md
Labels: documentation, doc update

#281 Experiment Vale Updates
  .github/styles/Amplitude/Adverbs.yml
  .github/styles/Amplitude/ComplexWords.yml
  .github/styles/Amplitude/Hyphens.yml
  .github/styles/Amplitude/Passive.yml
  .github/styles/Amplitude/TooWordy.yml
  .github/styles/Vocab/dev/accept.txt
  docs/experiment/general/data-model.md
  docs/experiment/general/exposure-tracking.md
  docs/experiment/general/performance-and-caching.md
  docs/experiment/index.md
Labels: documentation, doc update

#276 Update Intercom-cohort.md
  docs/data/destinations/intercom-cohort.md
Labels: documentation, doc update

#292 Add MetaRouter docs
  .github/styles/Vocab/dev/accept.txt
  docs/data/sources/metarouter.md
  includes/data-sources-other.md
  mkdocs.yml
  overrides/.icons/metarouter.svg
Labels: documentation

#291 Update event-streaming-integration-guide.md
  .github/styles/Vocab/dev/accept.txt
  docs/assets/images/partners/partner-customize-events-payload.png
  docs/assets/images/partners/partner-event-body-editor.png
  docs/assets/images/partners/partner-event-streaming-configuration.png
  docs/partners/event-streaming-integration-guide.md
  mkdocs.yml
Labels: documentation, big doc

#298 Disables lightboxing on a button that is actually an image
  includes/postman.md
Labels: bug

#294 Add Cordial Event Docs
  docs/data/sources/cordial.md
  includes/data-sources-other.md
  mkdocs.yml
Labels: documentation

#296 Add Moveable Ink Docs
  docs/data/destinations.md
  docs/data/destinations/moveable-ink-profile-api.md
  includes/data-destinations-user-profile-api.md
  mkdocs.yml
  overrides/.icons/moveable-ink.svg
Labels: documentation

#299 Add PII Data section and Osano docs
  .github/styles/Vocab/dev/accept.txt
  docs/data/index.md
  docs/data/pii.md
  docs/data/pii/osano.md
  includes/abbreviations.md
  includes/data-pii.md
  mkdocs.yml
  overrides/.icons/osano.svg
Labels: documentation, big doc

#301 docs: update ts browser sdk javascript snippet
  docs/data/sdks/java/ampli.md
  docs/data/sdks/typescript-browser/index.md
Labels: doc update

#300 DDI-99 ADD DATA GRAIL DOCS
  .github/styles/Amplitude/Headings.yml
  docs/data/destinations/moveable-ink-profile-api.md
  docs/data/pii/datagrail.md
  includes/data-pii.md
  mkdocs.yml
  overrides/.icons/datagrail.svg
Labels: documentation, big doc

#302 Add Talon.One docs
  .github/styles/Amplitude/Spacing.yml
  .github/styles/Vocab/dev/accept.txt
  docs/data/destinations/talonone-cohort.md
  includes/data-destinations-cohorts.md
  includes/editions-scholarship-growth-enterprise.md
  mkdocs.yml
  overrides/.icons/talonone.svg
Labels: documentation, new doc
